### ISSUE TITLE
Suppress warning - Unable to use the [locale] URL segment

### ISSUE THREAD

**Issue by jurrianlammerts** [Avansai/next-multilingual#20]
When starting my local dev server, I get an overload of warnings about the library not being able to use URL segments for specific page. However for these pages I'm using content from a CMS instead of static strings. So it's a bit annoying to get all these warnings everything I start up my dev server. 

```
warn  - unable to use the `en-GB` URL segment for `/Users/code/project/pages/[slug].jsx`. The message file `/Users/code/project/pages/[slug].en-GB.properties` does not exist.
```

Ultimately it would be nice to be able to suppress these kinds of warnings.

**Comment by nbouvrette** [comment]
@jurrianlammerts good catch - will push a release shortly to remove these warnings! Thanks for reporting it.

**Comment by nbouvrette** [comment]
@jurrianlammerts which version of `next-multilingual` are you using? I can no longer find this warning message in our code and this warning should be eliminated by this code here: https://github.com/Avansai/next-multilingual/blob/864075a54c47228edd865f7598302975b3ccb317/src/config/index.ts#L194

I'd suggest to update to get rid of the warning - let me know if this does not resolve the issue!

**Comment by jurrianlammerts** [comment]
@nbouvrette Thanks for the help! Upgrading to the latest version resolved the issue.

**Comment by jurrianlammerts** [comment]
After changing my config file to my needs, I came across the following: I do have static pages that are translated with content from the CMS, but without a dynamic `[slug]`. So I do understand why I still get this warning after adding all my pages back in the project: 
```
warn  - unable to create the en-GB slug for pages/contact.jsx. The message file pages/contact.en-GB.properties does not exist.
```
It still would be a nice option to be able to config these warnings!

**Comment by nbouvrette** [comment]
@jurrianlammerts can you explain a bit more the use case - are you saying you do not want to use the localized URLs? Unless I a missing something, you should be able to add slugs for static pages,

**Comment by jurrianlammerts** [comment]
@nbouvrette with static pages I mean the ones located in the `/pages` folder, for these pages I'm getting the warnings. I indeed don't use localized URLs.

**Comment by nbouvrette** [comment]
@jurrianlammerts this issue has been inactive for a while - I still have an open question in my last comment, feel free to comment and re-open if you have a chance!
