### ISSUE TITLE
Usage with i18next-scanner?

### ISSUE THREAD

**Issue by NielsvanHoof** [Avansai/next-multilingual#22]
Hey, like last time, currently in the progress of porting over from next-i18next to your package, and we came across another roadblock. 

We currently use a custom made CMS that allows content editors to fill in translations, these translations are scanned using the i18n-next scanner package. 

Next-i18n stores these as json files, e.g. at the moment we have a single common.json file that includes all of the translations the app has to offer. This is then loaded on every page using their serverSideTranslations function inside of getStaticProps. 

Now, your package has a file for every page e.g. [fileName].[locale].properties. 

e.g. if I have an about and an index page I need to create two properties file. 

Now i18next-scanner has the option to allow creation of properties files (it's just swapping the extension out afterall)

something like what we currently have 

```
   resource: {
      loadPath: "public/locales/{{lng}}/{{ns}}.json",
      savePath: "public/locales/{{lng}}/{{ns}}.json",
      jsonIndent: 2,
      lineEnding: "\n",
    },
```

we could probably change the load and save path extensions to end in .properties, but we're unsure on how to tackle the issue related to multiple pages. 

It would obviously be great if you could pass in an option to i18next-scanner that would allow the creation of a file sort of like the following.

```
    resource: {
      loadPath: "public/locales/{{lng}}/{{file}}/{{ns}}.properties",
      savePath: "public/locales/{{lng}}/{{file}}/{{ns}}.properties",
      jsonIndent: 2,
      lineEnding: "\n",
    },
```
Which would allow us to create .properties files dynamically. 

Do you have any advice for this? another solution would also be alright. 

Thank you!

**Comment by TomFreudenberg** [comment]
Hey @NielsvanHoof 

I am not yet as much familar with this component as on others but maybe you check the part of documentation about:

https://github.com/Avansai/next-multilingual#creating-shared-messages

That should advise you to use just 1 file for your translation and help you continuing the current process?

Cheers,
Tom

**Comment by nbouvrette** [comment]
Thanks @TomFreudenberg - I think your proposal looks like a good approach if I understood correctly the current problem. 

One thing I would keep an eye on is the size of the file. I'm not sure how `next-i18next` handles this but if you have a lot of content in a single file, your page load might become quite bad at some point which was one of the benefits behind `next-multilingual`

@NielsvanHoof, if you don't mind I have comments/questions that might be a bit out of scope with your questions but I was curious about your project. You gave an example about people writing the content of an "about" page. Is there a reason you would include this part of your CMS or maybe that was just an example? Typically CMSes would include some sort of embedded translation process and some of these solutions can also be done outside the CMS itself which could allow to manipulate files if needed.

Also if you are planning to translate in the CMS itself (just guessing here) there are drawbacks with this approach. For example, you would not benefit from the standard translation tools (like translation memory and terminology). But again I am not sure exactly what your project is. If you have people who can translate the content part of your team, that type of solution can also work well. But always keep in mind future expansions and such to avoid bad surprises later down the road.

We are hoping to release a CLI for continuous localization once we are happy with the `next-multilingual` features but I doubt this will happen this quarter.

**Comment by NielsvanHoof** [comment]
Hey, sorry for the late response been a few busy days.

First of all @TomFreudenberg solution has helped me so far, using a single file for everything.


@nbouvrette We are currently in the progress of porting over a legacy "cms" (think php 5.6 and jquery) over to a headless laravel 8 + inertia SPA with a next js frontend. My dev team has brought up a few alternatives (strapi, contentfull, sanity, e.t.c) but management would rather have us built something custom and in house, then rely on 3rd party software (we tried to reason with them, but alas).

Now our marketing team is also our editing team, they have the ability to do basic CRUD to pages and their content which can be translated inside of the CMS it self, while the custom components each editor can place are pre-translated.

I know it's a bit of a weird way of doing things, and trust me I tried to convince upper management to use something like locize but they are scared of 3rd party vendor lock in and what would happen if X company where to cease existing.

I hope this cleared up my use case for you, so far your package has been truly great and we appreciate the work you put into this!

**Comment by nbouvrette** [comment]
Thanks for the feedback @NielsvanHoof - on our side we had similar challenges regarding our CMS and we are planning to stay on WordPress (using a subdomain) until we find a better solution. But I totally get your challenge and am happy our package was able to help.

I'm doing to close this issue and by the way, I also enabled GitHub Discussions so feel free to use it as well if you have any topic you want to discuss in the future!
