### ISSUE TITLE
Use jest and enzyme for testing apps

### ISSUE THREAD

**Issue by TomFreudenberg** [Avansai/next-multilingual#28]
How to enable this component for writing tests of app?

When using e.g. next-translate we made following test:

__jest.config.js__

```js
import Enzyme from 'enzyme';
import Adapter from '@wojtekmaj/enzyme-adapter-react-17';
import i18n_config from './i18n';

// enable next-translate for testing
global.i18nConfig = i18n_config;

// append the react enzyme adapter
Enzyme.configure({ adapter: new Adapter() });
```

__test/examples/localeTest.js__

```js
import getT from 'next-translate/getT';

describe('Next translate', () => {
  it('should match the translated string', async () => {
    const t_en = await getT('en', 'common');
    const t_de = await getT('de', 'common');
    const text_en = t_en('Welcome');
    const text_de = t_de('Welcome');
    expect(text_en).toBe('Welcome');
    expect(text_de).toBe('Willkommen');
  });
});
```

---

Is there something similar to enable testing for own components with next-multilingual?

Thanks for your help in advance.

**Comment by TomFreudenberg** [comment]
Hi Nicolas @nbouvrette 

any idea how to use this for jest tests?

This is also a must have for our development workflow

**Comment by nbouvrette** [comment]
@TomFreudenberg we use Cypress, you can check the example tests [here](https://github.com/Avansai/next-multilingual/tree/main/cypress/integration).

Cypress should be more than able to cover the example you provided.

If you really want to use Jest I am sure there is a way to make it work but I don't have any experience using it with Next.js applications.

I'm going to close this for now since this was more of a question than an actionable issue.

**Comment by TomFreudenberg** [comment]
> Cypress should be more than able to cover the example you provided.

Sorry - but - NO

Cypress is a tool you can use in addition for an E2E testing but with jest and the integration React testing, we are able to write mountable unit tests and ci without having the need to run a server somewhere. Also we can cover tests from component internals what is not possible from E2E tests.

So it is not a question but a feature request that this should be possible as it is for other i18n components as well.

I guess that it is the same as for storybook - the babel plugin must be integration in jest warm up process.

**Comment by nbouvrette** [comment]
You might want to check at this:

https://www.cypress.io/blog/2021/04/06/cypress-component-testing-react/

> The Cypress Component Test Runner is an alternative to a jsdom based testing environment, such as Jest and Vue Test Utils. 

I'm not sure what feature is required to use Jest because we don't use it (and it's impossible for us to use/test all tools out there). If you know what is missing (if anything) we can re-open this as a feature request, and even consider a PR :)

**Comment by TomFreudenberg** [comment]
Getting closer on this - first test already works

**Comment by TomFreudenberg** [comment]
Could you please advise me here:

```js
export function getMessages(locale: string): Messages {
  return handleMessages(this, 'getMessages', locale.toLowerCase());
}
```

from messages/index.tsx

When and were is `this` getting initialized as BabilifiedMessages?

**Comment by TomFreudenberg** [comment]
Ok, I got the issue.

while working on my fork I had not set the fileExtension to load. Therefor the files could not be located.

But when using your original it is missing wile the babel on jest is running BEFORE initialization of `new Config`. Therefore `applicationId` is not set. 

I solved that on my fork due to params opts from .babelrc

**Comment by TomFreudenberg** [comment]
I have fixed that in the derived package at:

https://github.com/4commerce-technologies-AG/next-multilingual-alternate

With that package you can use `jest` and `enzyme` for any kind of component testing like:

```js
import { getFruitsMessages } from '@/imports/i18n/fruits';

describe('Next translate', () => {
  it('should match the translated string', async () => {
    const lang_de_DE = 'de-DE';
    const lang_en_US = 'en-US';
    const fruitsMessages_de_DE = getFruitsMessages(lang_de_DE);
    const fruitsMessages_en_US = getFruitsMessages(lang_en_US);
    expect(fruitsMessages_de_DE.format('apple pie')).toBe('Apfelkuchen');
    expect(fruitsMessages_en_US.format('apple pie')).toBe('apple pie');
  });
});
```

or with mounting and router:

```js
import * as React from 'react';
import { mount, shallow, render } from 'enzyme';
import Welcome from '@/imports/ui/welcome';
import { withTestRouter } from '@/tests/imports/withTestRouter';
import { useFruitsMessages } from '@/imports/i18n/fruits';

const LocaleWelcome = function ({ locale_message }) {
  const fruitsMessages = useFruitsMessages();
  return <Welcome message={fruitsMessages.format(locale_message)} />;
};

describe('Pages', () => {
  describe('Welcome', () => {
    it('should render without throwing an error', () => {
      const wrap = mount(withTestRouter(<LocaleWelcome locale_message="apple pie" />, { locale: 'de-DE' }));
      expect(wrap.find('div').text()).toBe('Apfelkuchen');
    });
  });
});
```

If some wants to know more in detail, please come up to [our issue list](https://github.com/4commerce-technologies-AG/next-multilingual-alternate/issues).

Cheers
Tom
