### ISSUE TITLE
Using storybook fails

### ISSUE THREAD

**Issue by TomFreudenberg** [Avansai/next-multilingual#29]
Hi,

do you have some information about how to use next-multilingual within storybook?

Current output when including e.g. `useMessages`

<pre>
ModuleNotFoundError: Module not found: Error: Can't resolve 'os' in './next-multilingual/node_modules/next/dist/compiled/chalk'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
</pre>

**Comment by TomFreudenberg** [comment]
Hi Nicolas @nbouvrette 

do you have any idea how to enable (at least the default lang) into storybook?

I have already disabled the non available packages

```js

    # main.js from .storybook

    webpackFinal: async (config) => {

    config.resolve.fallback['os'] = false;
    config.resolve.fallback['fs'] = false;
    config.resolve.fallback['util'] = false;
    config.resolve.fallback['tty'] = false;
    config.resolve.fallback['events'] = false;

    return config;
  },
```

and also include an initialization in `preview.js` but it looks like the babel-plugin is not running while running the storybook server or build.

This is a must have for our development workflow

**Comment by nbouvrette** [comment]
I presume you mean this? https://storybook.js.org/

I am not familiar with Storybook so I would not be able to help. We are using https://chakra-ui.com/ on our side and it's working well. Presumably, something in Storybook is causing issues - let me know if you find what and if we can apply a fix.

The Chalk error you provided seems related to an old version of `next-multilingual` - maybe you can try to update it.. we no longer use Chalk.

**Comment by TomFreudenberg** [comment]
> The Chalk error you provided seems related to an old version of `next-multilingual` - maybe you can try to update it.. we no longer use Chalk.

I use the actual stable release 0.10.3.

Not sure from where the Chalk dependency comes from but it's still somewhere in current release (?)

**Comment by TomFreudenberg** [comment]
> We are using https://chakra-ui.com/ on our side and it's working well.

Chakra-UI is for frontend design - for that we are working with MUI v5 and that is working as well.

> I presume you mean this? https://storybook.js.org/

Storybook is a tool for writing components during development and design as small "items" to test conditions and props without mounting it in the final app or running a test. Just to have a "what does it look like and what are the functions overall from your components"

That's one of our main development strategies - you should check that if you not familar yet - I recommend that to you.

**Comment by TomFreudenberg** [comment]
> Presumably, something in Storybook is causing issues

As far as I have debugged that until now, the babel plugin gets not started in storybook, even that I have added that plugin there.

Debugging is awefull with storybook because you dont't get all the output. I am not familar in deep with babel so it might an easy step but I can't see.

Any help or tip would be useful.

**Comment by nbouvrette** [comment]
> Not sure from where the Chalk dependency comes from but it's still somewhere in current release (?)

It's not: https://github.com/Avansai/next-multilingual/search?q=chalk

You probably have to figure out where this error is coming from but it's not `next-multilingual`

> As far as I have debugged that until now, the babel plugin gets not started in storybook, even that I have added that plugin there.
> 
> Debugging is awefull with storybook because you dont't get all the output. I am not familar in deep with babel so it might an easy step but I can't see.

Definitely, you need to make sure the Babel plugin is run otherwise nothing will work - maybe I would suggest checking with them first to make sure this step works and if you have issues after this we can figure out how I can give you a quick hand

**Comment by nbouvrette** [comment]
I'm going to close this since there is no direct issue to fix. Please feel free to share any interesting find using a [discussion](https://github.com/Avansai/next-multilingual/discussions).
