### ISSUE TITLE
Localized URL throws SEO warning on Lighthouse

### ISSUE THREAD

**Issue by artClown** [Avansai/next-multilingual#31]
First, absolutely love this package. Just one (minor?) issue, though. When I try the demo app, for example [this page](https://next-multilingual-example.vercel.app/fr-ca/nous-joindre) and run it through Lighthouse, I got a warning that the document doesn't have a valid `rel=canonical`. 

The `rel=canonical` for that particular page is `<link rel="canonical" href="https://next-multilingual-example.vercel.app/en-us/contact-us">`. Shouldn't it be `<link rel="canonical" href="https://next-multilingual-example.vercel.app/fr-ca/nous-joindre">`?

**Comment by artClown** [comment]
Hi @nbouvrette, I just tried again using [https://next-multilingual-example.vercel.app/fr-ca/nous-joindre](https://next-multilingual-example.vercel.app/fr-ca/nous-joindre) on lighthouse and [web dev](https://web.dev/measure/). 

On both test, `rel=canonical` is invalid because the page is in `fr-ca` however the `rel=canonical` points to `en-us` page. Please note that the issue only comes up on non-default(?) locale as the `rel=canonical` is set to be on the same locale as the default locale.

Here is a screenshot of lighthouse result - SEO section:
<img width="756" alt="Screen Shot 2022-06-02 at 21 08 32" src="https://user-images.githubusercontent.com/66511241/171648435-b96951b9-535d-44c4-935f-7eef8dde2f46.png">

And the one from web.dev:
<img width="951" alt="Screen Shot 2022-06-02 at 21 10 02" src="https://user-images.githubusercontent.com/66511241/171648657-9fc9e3aa-29fa-48bd-8a46-8d8b44a880fb.png">

**Comment by nbouvrette** [comment]
Thanks for reporting this bug @artClown - the fix has been released in 0.11.2!
