### ISSUE TITLE
invalid locale `en` . `next-multilingual` only uses locale identifiers following the `language`-`country` format

### ISSUE THREAD

**Issue by kosmokoks** [Avansai/next-multilingual#33]
Hello,

It's possible to have the only 'language' format without the country? For example in route you have the 'en/products' instead of 'en-us/products'?

**Comment by nbouvrette** [comment]
Hi @kosmokoks 

`next-multilingual` has been designed to avoid ambiguity which is one of the major flaws that a lot of i18n solutions today are willing to support.

If you look at our [design decision document](https://github.com/Avansai/next-multilingual/blob/main/docs/design-decisions.md#design-decisions-1) we have a full section that explains why we don't believe that supporting language tags (without countries) is problematic:

> 1. There is no such concept as a "regionless" variant of a language. Even English might seem like a simple language but there are many nuances between English U.S. and English U.K. By not specifying which variant is used, the content creator or the translator will have to decide, and this can lead to inconsistency.
> 2. On top of using different expressions, there are many other differences such as date, currency, or number formats. If a site is using none of these, it might sound acceptable to simply use a language code but there are few use cases where this would apply.
> 3. SEO: by targeting better the language with a country, your results will be more relevant in the search results of those countries - [Moz, 2021](https://moz.com/learn/seo/international-seo)

**Comment by marekmaurizio** [comment]
What if i want it anyway? Is it possibile or should i look somewhere else?
