### ISSUE TITLE
Error: locales must be configured in Next.js

### ISSUE THREAD

**Issue by NitrousBGC** [Avansai/next-multilingual#34]
Hey,

I'm starting to do the migration to next-multilingual from next-I18next and after adding the custom doc i get this error.

Here is the log : 
`Error: locales must be configured in Next.js
    at getActualLocale (E:\Documents\SITES\TC Renhouse\tc-renhouse\node_modules\next-multilingual\lib\index.js:94:15)
    at MyDocument.render (webpack-internal:///./pages/_document.tsx:28:140)
    at finishClassComponent (E:\Documents\SITES\TC Renhouse\tc-renhouse\node_modules\react-dom\cjs\react-dom-server-legacy.browser.development.js:5666:31)
    at renderClassComponent (E:\Documents\SITES\TC Renhouse\tc-renhouse\node_modules\react-dom\cjs\react-dom-server-legacy.browser.development.js:5699:3)
    at renderElement (E:\Documents\SITES\TC Renhouse\tc-renhouse\node_modules\react-dom\cjs\react-dom-server-legacy.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (E:\Documents\SITES\TC Renhouse\tc-renhouse\node_modules\react-dom\cjs\react-dom-server-legacy.browser.development.js:6107:11)
    at renderNodeDestructive (E:\Documents\SITES\TC Renhouse\tc-renhouse\node_modules\react-dom\cjs\react-dom-server-legacy.browser.development.js:6079:14)
    at renderContextProvider (E:\Documents\SITES\TC Renhouse\tc-renhouse\node_modules\react-dom\cjs\react-dom-server-legacy.browser.development.js:5923:3)
    at renderElement (E:\Documents\SITES\TC Renhouse\tc-renhouse\node_modules\react-dom\cjs\react-dom-server-legacy.browser.development.js:6020:11)
    at renderNodeDestructiveImpl (E:\Documents\SITES\TC Renhouse\tc-renhouse\node_modules\react-dom\cjs\react-dom-server-legacy.browser.development.js:6107:11)`

Could someone point me in the right direction ?

Thanks !

**Comment by dube25** [comment]
Hi @NitrousBGC, 
have you declared your project's supported locales as mentioned in the guide?

https://github.com/Avansai/next-multilingual#step-by-step-configuration-%EF%B8%8F

**Comment by dube25** [comment]
@NitrousBGC : On a side note, this project[ does not have a migration guide from next-I18next ](https://github.com/Avansai/next-multilingual/issues/8), which would be a great addition to help others make the move. 

If by any chance you've documented your steps, sharing it would be a great way to contribute to the community. Docs are located [here](https://github.com/Avansai/next-multilingual/tree/main/docs).

**Comment by NitrousBGC** [comment]
> @NitrousBGC : On a side note, this project[ does not have a migration guide from next-I18next ](https://github.com/Avansai/next-multilingual/issues/8), which would be a great addition to help others make the move.
> 
> If by any chance you've documented your steps, sharing it would be a great way to contribute to the community. Docs are located [here](https://github.com/Avansai/next-multilingual/tree/main/docs).

**Little update about the issue:** 
It was caused by a conflict between **next-translate-routes** and next-multilingual.

I had to carefully remove every import or reference to **next-translate-routes** and the error went right away. (Debugging with the exemple was definitely a good idea!) 

About the migration guide I didn't thought about documenting it. I tried all kind of different stuff but I could probably do it again. If the project is small and mostly static the transition isn't that hard, but I can imagine the hell if we are talking about hundreds of pages. 
I'm working on a site for a customer for the moment but I could try as soon as I finish it. The only real problem is probably my english. I'm not native and I'm still learning on the go. Also, my github knowledge is basic, I started using it recently.

If someone can do some proofreading on the migration guide I'll be happy to give it a shot!


Thanks again for the help!

**Comment by NitrousBGC** [comment]
Hey,

I'm coming back with another question...
First of all I finished the transition between **next-I18next** and **next-translate-route** to **_next-multilingual_**.
Everything works as expected (it's really wonderful) and it took me about **12 hours** to convert all the translation files and translations keys. (site translated in 3 languages)

**My question is:** 
Can I also use next-multilingual to output a sitemap with alternate refs for the translated pages ? I'm using next-sitemap for the moment but it's only outputting the original links (original filenames). Or is it something that could be implemented later?

I'm wondering because the opinions on sitemaps are not always the same... Is it enough to just work with rel=alternate hreflang?

Thanks! 😄

**Comment by nbouvrette** [comment]
Great to hear @NitrousBGC !

Regarding the sitemap, we originally had it on our backlog but while researching on it, other than giving a pointer to Google to trigger manual scans (using the Google SEO tools), sitemaps should no longer be required to crawl and index your site if the pages are correctly linked together.

Also based on Google's best practice, you should not have multilingual sitemaps when you use the correct headers that are provided out of the box with next-multilingual.

So basically if you really want a sitemap, you can just generate a standard one using English URLs and the next-multilingual HTML headers will tell Google what are the equivalent pages in other languages.

On our side (in our projects using next-multilingual), we decided to abandon sitemaps - it felt like a technology from the past. But if you really want to use them, I think you have many options to do so when using next-multilingual.

Hopefully this helps!

(By the way, I will close this issue for now. Feel free to open [discussions](https://github.com/Avansai/next-multilingual/discussions) or other issues if you need anything!)
