### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by shusiner** [Avansai/next-multilingual#40]
Missing link at:

https://github.com/Avansai/next-multilingual/blob/bb8c923b3d5f9c9bd81b8f8c6a4035cacf0f1cce/README.md?plain=1#LL1205C135-L1205C135

https://github.com/Avansai/next-multilingual/blob/main/doc, not found

**Comment by nbouvrette** [comment]
Congratulation @shusiner you found our easter egg to see if anyone was reading our readme 🎉🎉

Jokes aside, thanks for reporting this - I updated the readme with the correct URL: https://github.com/Avansai/next-multilingual/tree/main/docs
