### ISSUE TITLE
This is not an issue

### ISSUE THREAD

**Issue by joestaxk** [Avansai/next-multilingual#41]
I love what you guys are doing, i have been following up with this project, I would love to contribute or give a little help that I can.

**Comment by nbouvrette** [comment]
thanks for the positive words @joestaxk - the next big thing for this package would probably be to support the `/app` directory of Next.js. That would require to rewrite the Babel plugin in SWC which is something we started investigating - not sure if this fits your expertise but if you think you can help with this please let me know!

**Comment by nbouvrette** [comment]
Going to close this for now since it's not an isssue 😊
