### ISSUE TITLE
Support next@13?

### ISSUE THREAD

**Issue by monolithed** [Avansai/next-multilingual#43]
Does this library work with the 'app' directory from next@13?

**Comment by nbouvrette** [comment]
The localized URL transation won't work - I would need to rewrite completely the logic.

The "message module" functionality might work if you use Babel but I think Next.js is slowly moving to SWC which means I would need to rewrite this capability in Rust.

In a nutshell, lot of work would be required to make this work and at the moment I have no active project that would drive me ot build these missing feature unfortunately.

If you are interested in collaborating on these type of projects in some shape or form, let me know and we could discuss more in details.
